nodes:
  - name: zed_cloud_to_base
    type: pointcloud_transformer
    input_topic: /camera/left_camera/points
    output_topic: /camera/points/filtered/base
    target_frame: base_link

  - name: left_camera_scan
    type: pointcloud_to_laserscan
    input_cloud_topic: /camera/points/filtered/base
    output_scan_topic: /camera/scan
    target_frame: base_link
    transform_tolerance: 0.01
    min_height: 0.0
    max_height: 1.0
    angle_min: -1.5708 # -pi/2
    angle_max: 1.5708  # pi/2`
    angle_increment: 0.00872665 # pi/360.0
    range_min: 0.5
    range_max: 20.0
    scan_time: 0.03333
    use_inf: True
    inf_epsilon: 1.0
